# jwt configuration
jwt:
  expires-at: 24h # 24h == 1天 默认设置为1天
  refresh-at: 24h # 24h == 1天 , 24h * 7 = 168h 刷新的token设置为一星期
  signing-key: 'SliverHorn'

# gorm configuration
gorm:
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  log-zap: ""
  log-mode: false
  auto-migrate: true
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-lifetime: 1h
  conn-max-idle-time: 24h
  dsn:
    sources:
      - host: '127.0.0.1'
        port: '13307'
        db-name: 'gf_vue_admin'
        username: 'root'
        password: 'gdkid,,..'
#      - host: '127.0.0.1'
#        port: '5432'
#        db-name: 'gin-vue-admin-business'
#        username: 'root'
#        password: 'gdkid,,..'
#    replicas:
#      - host: '127.0.0.1'
#        port: '5432'
#        db-name: 'gin-vue-admin-business'
#        username: 'root'
#        password: 'gdkid,,..'
#      - host: '127.0.0.1'
#        port: '5432'
#        db-name: 'gin-vue-admin-business'
#        username: 'root'
#        password: 'gdkid,,..'

# redis configuration
redis:
  db: 0
  address: '127.0.0.1:6379'
  password: ''

# email configuration
email:
  to: 'xxx@qq.com'
  port: 465
  from: 'xxx@163.com'
  host: 'smtp.163.com'
  is-ssl: true
  secret: 'xxx'
  nickname: 'test'

# casbin configuration
casbin:
  model-path: './public/rbac_model.conf'

# system configuration
system:
  env: 'public' # Change to 'develop' to skip authentication for development mode
  db-type: 'mysql'
  orm-type: 'gdb'
  language: 'zh-CN'
  oss-type: 'local'
  error-to-email: false
  use-multipoint: false

# captcha configuration
captcha:
  key-long: 6
  image-width: 240
  image-height: 80
  captcha-in-redis: false

# local configuration
local:
  path: 'uploads/file'

# qiniu configuration (请自行七牛申请对应的 公钥 私钥 bucket 域名地址)
qiniu:
  zone: 'ZoneHuaDong' # 配置请看server/integration/upload/internal/qiniu.go
  bucket: ''
  img-path: ''
  use-https: false
  access-key: ''
  secret-key: ''
  use-cdn-domains: false

# minio configuration
minio:
  id: 'minio'
  path: 'http://localhost:9000'
  token: ''
  bucket: 'public'
  use-ssl: false
  secret: 'minio'
  endpoint: 'localhost:9000'

# aliyun configuration
aliyun:
  path: 'https://xxx.oss-cn-beijing.aliyuncs.com'
  bucket: ''
  acl-type: ''
  endpoint: 'https://oss-cn-beijing.aliyuncs.com'
  access-key-id: ''
  secret-access-key: ''
  storage-class-type: 'Standard' # 配置请看server/integration/upload/internal/aliyun.go

# tencent configuration
tencent-cos:
  bucket: ''
  region: 'ap-shanghai'
  secret-id: ''
  secret-key: ''
  base-url: 'https://gin.vue.admin'
  path-prefix: 'gin-vue-admin'


# uploader configuration
uploader:
  chunk-dir: './chunk/'
  finish-dir: './finish/'