name: gva build test

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "./db/**"
      - "**.md"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "./db/**"
      - "**.md"

jobs:
  backend:
    name: Backend build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out branch
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
        working-directory: ./server

      - name: Test and Build
        run: |
          go build -tags "mysql" -v -race cmd/main.go
          go build -tags "postgres" -v -race cmd/main.go
        working-directory: ./server